# A simple Makefile for CPSC 360
CC = g++

CFLAGS= -framework CoreFoundation -framework OPENGL -framework GLUT -lm

INCS=

# the source files to be built
SOURCES = *.cpp ./soil/*c

# object files
OBJS = *.o

# the name of the executable
PROG = final

# executable file extension
BINEXT = .exe

all:
	$(CC) -DMAC $(SOURCES) -o $(PROG)$(BINEXT) $(CFLAGS)


# this line required by make - don't delete
